# This file is auto-generated by h2o-3/h2o-bindings/bin/gen_R.py
# Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details) 
#'
# -------------------------- H2O InfoGram -------------------------- #
#'
#' Given a sensitive/unfair predictors list, InfoGram will add all predictors that contains information on the 
#'  sensitive/unfair predictors list to the sensitive/unfair predictors list.  It will return a set of predictors that
#'  do not contain information on the sensitive/unfair list and hence user can build a fair model.  If no sensitive/unfair
#'  predictor list is given, InfoGram will return a list of core predictors that should be used to build a final model.
#'  InfoGram can significantly cut down the number of predictors needed to build a model and hence will build a simple
#'  model that is more interpretable, less susceptible to overfitting, runs faster while providing similar accuracy
#'  as models built using all attributes.
#' 
#'
#' @param x (Optional) A vector containing the names or indices of the predictor variables to use in building the model.
#'        If x is missing, then all columns except y are used.
#' @param y The name or column index of the response variable in the data. 
#'        The response must be either a numeric or a categorical/factor variable. 
#'        If the response is numeric, then a regression model will be trained, otherwise it will train a classification model.
#' @param training_frame Id of the training data frame.
#' @param model_id Destination id for this model; auto-generated if not specified.
#' @param validation_frame Id of the validation data frame.
#' @param seed Seed for random numbers (affects certain parts of the algo that are stochastic and those might or might not be enabled by default).
#'        Defaults to -1 (time-based random number).
#' @param keep_cross_validation_models \code{Logical}. Whether to keep the cross-validation models. Defaults to TRUE.
#' @param keep_cross_validation_predictions \code{Logical}. Whether to keep the predictions of the cross-validation models. Defaults to FALSE.
#' @param keep_cross_validation_fold_assignment \code{Logical}. Whether to keep the cross-validation fold assignment. Defaults to FALSE.
#' @param fold_assignment Cross-validation fold assignment scheme, if fold_column is not specified. The 'Stratified' option will
#'        stratify the folds based on the response variable, for classification problems. Must be one of: "AUTO",
#'        "Random", "Modulo", "Stratified". Defaults to AUTO.
#' @param fold_column Column with cross-validation fold index assignment per observation.
#' @param ignore_const_cols \code{Logical}. Ignore constant columns. Defaults to TRUE.
#' @param score_each_iteration \code{Logical}. Whether to score during each iteration of model training. Defaults to FALSE.
#' @param offset_column Offset column. This will be added to the combination of columns before applying the link function.
#' @param weights_column Column with observation weights. Giving some observation a weight of zero is equivalent to excluding it from
#'        the dataset; giving an observation a relative weight of 2 is equivalent to repeating that row twice. Negative
#'        weights are not allowed. Note: Weights are per-row observation weights and do not increase the size of the
#'        data frame. This is typically the number of times a row is repeated, but non-integer values are supported as
#'        well. During training, rows with higher weights matter more, due to the larger loss function pre-factor.
#' @param standardize \code{Logical}. Standardize numeric columns to have zero mean and unit variance Defaults to FALSE.
#' @param plug_values Plug Values (a single row frame containing values that will be used to impute missing values of the
#'        training/validation frame, use with conjunction missing_values_handling = PlugValues)
#' @param max_iterations Maximum number of iterations Defaults to 0.
#' @param stopping_rounds Early stopping based on convergence of stopping_metric. Stop if simple moving average of length k of the
#'        stopping_metric does not improve for k:=stopping_rounds scoring events (0 to disable) Defaults to 0.
#' @param stopping_metric Metric to use for early stopping (AUTO: logloss for classification, deviance for regression and
#'        anonomaly_score for Isolation Forest). Note that custom and custom_increasing can only be used in GBM and DRF
#'        with the Python client. Must be one of: "AUTO", "deviance", "logloss", "MSE", "RMSE", "MAE", "RMSLE", "AUC",
#'        "AUCPR", "lift_top_group", "misclassification", "mean_per_class_error", "custom", "custom_increasing".
#'        Defaults to AUTO.
#' @param stopping_tolerance Relative tolerance for metric-based stopping criterion (stop if relative improvement is not at least this
#'        much) Defaults to 0.001.
#' @param balance_classes \code{Logical}. Balance training data class counts via over/under-sampling (for imbalanced data). Defaults to
#'        FALSE.
#' @param class_sampling_factors Desired over/under-sampling ratios per class (in lexicographic order). If not specified, sampling factors will
#'        be automatically computed to obtain class balance during training. Requires balance_classes.
#' @param max_after_balance_size Maximum relative size of the training data after balancing class counts (can be less than 1.0). Requires
#'        balance_classes. Defaults to 5.0.
#' @param max_runtime_secs Maximum allowed runtime in seconds for model training. Use 0 to disable. Defaults to 0.
#' @param custom_metric_func Reference to custom evaluation function, format: `language:keyName=funcName`
#' @param auc_type Set default multinomial AUC type. Must be one of: "AUTO", "NONE", "MACRO_OVR", "WEIGHTED_OVR", "MACRO_OVO",
#'        "WEIGHTED_OVO". Defaults to AUTO.
#' @param infogram_algorithm Machine learning algorithm chosen to build the infogram.  AUTO default to GBM Must be one of: "AUTO",
#'        "deeplearning", "drf", "gbm", "glm". Defaults to gbm.
#' @param infogram_algorithm_params parameters specified to the chosen algorithm can be passed to infogram using algorithm_params
#' @param model_algorithm Machine learning algorithm chosen to build the final model.  AUTO default to GBM Must be one of: "AUTO",
#'        "deeplearning", "drf", "gbm", "glm". Defaults to gbm.
#' @param model_algorithm_params parameters specified to the chosen final algorithm
#' @param sensitive_attributes predictors that are to be excluded from model due to them being discriminatory or inappropriate for whatever
#'        reason.
#' @param conditional_info_threshold conditional information threshold between 0 and 1 that is used to decide whether a predictor's conditional
#'        information is high enough.  Default to 0.1 Defaults to 0.1.
#' @param varimp_threshold variable importance threshold between 0 and 1 that is used to decide whether a predictor's relevance level is
#'        high enough.  Default to 0.1 Defaults to 0.1.
#' @param data_fraction fraction of training frame to use to build the infogram model.  Default to 1.0 Defaults to 1.
#' @param parallelism number of models to build in parallel.  Default to 0.0 which is adaptive to the system capability Defaults to
#'        0.
#' @param ntop number of top k variables to consider based on the varimp.  Default to 0.0 which is to consider all predictors
#'        Defaults to 50.
#' @param compute_p_values \code{Logical}. If true will calculate the p-value. Default to false Defaults to FALSE.
#' @examples
#' \dontrun{
#' h2o.init()
#' 
#' # Run GAM of CAPSULE ~ AGE + RACE + PSA + DCAPS
#' prostate_path <- system.file("extdata", "prostate.csv", package = "h2o")
#' prostate <- h2o.uploadFile(path = prostate_path)
#' prostate$CAPSULE <- as.factor(prostate$CAPSULE)
#' h2o.gam(y = "CAPSULE", x = c("RACE"), gam_columns = c("PSA"),
#'      training_frame = prostate, family = "binomial")
#' 
#' }
#' @export
h2o.infogram <- function(x,
                         y,
                         training_frame,
                         gam_columns,
                         model_id = NULL,
                         validation_frame = NULL,
                         seed = -1,
                         keep_cross_validation_models = TRUE,
                         keep_cross_validation_predictions = FALSE,
                         keep_cross_validation_fold_assignment = FALSE,
                         fold_assignment = c("AUTO", "Random", "Modulo", "Stratified"),
                         fold_column = NULL,
                         ignore_const_cols = TRUE,
                         score_each_iteration = FALSE,
                         offset_column = NULL,
                         weights_column = NULL,
                         standardize = FALSE,
                         plug_values = NULL,
                         max_iterations = 0,
                         stopping_rounds = 0,
                         stopping_metric = c("AUTO", "deviance", "logloss", "MSE", "RMSE", "MAE", "RMSLE", "AUC", "AUCPR", "lift_top_group", "misclassification", "mean_per_class_error", "custom", "custom_increasing"),
                         stopping_tolerance = 0.001,
                         balance_classes = FALSE,
                         class_sampling_factors = NULL,
                         max_after_balance_size = 5.0,
                         max_runtime_secs = 0,
                         custom_metric_func = NULL,
                         auc_type = c("AUTO", "NONE", "MACRO_OVR", "WEIGHTED_OVR", "MACRO_OVO", "WEIGHTED_OVO"),
                         infogram_algorithm = c("AUTO", "deeplearning", "drf", "gbm", "glm"),
                         infogram_algorithm_params = NULL,
                         model_algorithm = c("AUTO", "deeplearning", "drf", "gbm", "glm"),
                         model_algorithm_params = NULL,
                         sensitive_attributes = NULL,
                         conditional_info_threshold = 0.1,
                         varimp_threshold = 0.1,
                         data_fraction = 1,
                         parallelism = 0,
                         ntop = 50,
                         compute_p_values = FALSE)
{
  # Validate required training_frame first and other frame args: should be a valid key or an H2OFrame object
  training_frame <- .validate.H2OFrame(training_frame, required=TRUE)
  validation_frame <- .validate.H2OFrame(validation_frame, required=FALSE)

  # Validate other required args
  # If x is missing, no predictors will be used.  Only the gam columns are present as predictors
  if (missing(x) && infogram_algorithm_params=='GAM') {
      x = NULL
  } else {
      stop("predictor columns x must be specified except for GAM.")
  }

  # Validate other args
  # if (!is.null(beta_constraints)) {
  #     if (!inherits(beta_constraints, 'data.frame') && !is.H2OFrame(beta_constraints))
  #       stop(paste('`beta_constraints` must be an H2OH2OFrame or R data.frame. Got: ', class(beta_constraints)))
  #     if (inherits(beta_constraints, 'data.frame')) {
  #       beta_constraints <- as.h2o(beta_constraints)
  #     }
  # }
  if (inherits(beta_constraints, 'data.frame')) {
    beta_constraints <- as.h2o(beta_constraints)
  }

  # Build parameter list to send to model builder
  parms <- list()
  parms$training_frame <- training_frame
  args <- .verify_dataxy(training_frame, x, y)
  if( !missing(offset_column) && !is.null(offset_column))  args$x_ignore <- args$x_ignore[!( offset_column == args$x_ignore )]
  if( !missing(weights_column) && !is.null(weights_column)) args$x_ignore <- args$x_ignore[!( weights_column == args$x_ignore )]
  if( !missing(fold_column) && !is.null(fold_column)) args$x_ignore <- args$x_ignore[!( fold_column == args$x_ignore )]
  parms$ignored_columns <- args$x_ignore
  parms$response_column <- args$y
  parms$gam_columns <- gam_columns

  if (!missing(model_id))
    parms$model_id <- model_id
  if (!missing(validation_frame))
    parms$validation_frame <- validation_frame
  if (!missing(seed))
    parms$seed <- seed
  if (!missing(keep_cross_validation_models))
    parms$keep_cross_validation_models <- keep_cross_validation_models
  if (!missing(keep_cross_validation_predictions))
    parms$keep_cross_validation_predictions <- keep_cross_validation_predictions
  if (!missing(keep_cross_validation_fold_assignment))
    parms$keep_cross_validation_fold_assignment <- keep_cross_validation_fold_assignment
  if (!missing(fold_assignment))
    parms$fold_assignment <- fold_assignment
  if (!missing(fold_column))
    parms$fold_column <- fold_column
  if (!missing(ignore_const_cols))
    parms$ignore_const_cols <- ignore_const_cols
  if (!missing(score_each_iteration))
    parms$score_each_iteration <- score_each_iteration
  if (!missing(offset_column))
    parms$offset_column <- offset_column
  if (!missing(weights_column))
    parms$weights_column <- weights_column
  if (!missing(standardize))
    parms$standardize <- standardize
  if (!missing(plug_values))
    parms$plug_values <- plug_values
  if (!missing(max_iterations))
    parms$max_iterations <- max_iterations
  if (!missing(stopping_rounds))
    parms$stopping_rounds <- stopping_rounds
  if (!missing(stopping_metric))
    parms$stopping_metric <- stopping_metric
  if (!missing(stopping_tolerance))
    parms$stopping_tolerance <- stopping_tolerance
  if (!missing(balance_classes))
    parms$balance_classes <- balance_classes
  if (!missing(class_sampling_factors))
    parms$class_sampling_factors <- class_sampling_factors
  if (!missing(max_after_balance_size))
    parms$max_after_balance_size <- max_after_balance_size
  if (!missing(max_runtime_secs))
    parms$max_runtime_secs <- max_runtime_secs
  if (!missing(custom_metric_func))
    parms$custom_metric_func <- custom_metric_func
  if (!missing(auc_type))
    parms$auc_type <- auc_type
  if (!missing(infogram_algorithm))
    parms$infogram_algorithm <- infogram_algorithm
  if (!missing(model_algorithm))
    parms$model_algorithm <- model_algorithm
  if (!missing(sensitive_attributes))
    parms$sensitive_attributes <- sensitive_attributes
  if (!missing(conditional_info_threshold))
    parms$conditional_info_threshold <- conditional_info_threshold
  if (!missing(varimp_threshold))
    parms$varimp_threshold <- varimp_threshold
  if (!missing(data_fraction))
    parms$data_fraction <- data_fraction
  if (!missing(parallelism))
    parms$parallelism <- parallelism
  if (!missing(ntop))
    parms$ntop <- ntop
  if (!missing(compute_p_values))
    parms$compute_p_values <- compute_p_values

  if (!missing(infogram_algorithm_params))
      parms$infogram_algorithm_params <- as.character(toJSON(infogram_algorithm_params, pretty = TRUE))
  if (!missing(model_algorithm_params))
      parms$model_algorithm_params <- as.character(toJSON(model_algorithm_params, pretty = TRUE))
  if( !missing(interactions) ) {
      # interactions are column names => as-is
      if( is.character(interactions) )       parms$interactions <- interactions
        else if( is.numeric(interactions) )    parms$interactions <- names(training_frame)[interactions]
        else stop("Don't know what to do with interactions. Supply vector of indices or names")
  }
      # For now, accept nfolds in the R interface if it is 0 or 1, since those values really mean do nothing.
      # For any other value, error out.
      # Expunge nfolds from the message sent to H2O, since H2O doesn't understand it.
  if (!missing(nfolds) && nfolds > 1)
      parms$nfolds <- nfolds
  if(!missing(beta_constraints))
      parms$beta_constraints <- beta_constraints
      if(!missing(missing_values_handling))
          parms$missing_values_handling <- missing_values_handling

  # Error check and build model
  model <- .h2o.modelJob('infogram', parms, h2oRestApiVersion=99, verbose=FALSE)

  # Convert infogram_algorithm_params back to list if not NULL
  if (!missing(infogram_algorithm_params)) {
      model@parameters$infogram_algorithm_params <- list(fromJSON(model@parameters$infogram_algorithm_params))[[1]] #Need the `[[ ]]` to avoid a nested list
  }
  if (!missing(model_algorithm_params)) {
      model@parameters$model_algorithm_params <- list(fromJSON(model@parameters$model_algorithm_params))[[1]] #Need the `[[ ]]` to avoid a nested list
  }
  return(model)
}
.h2o.train_segments_infogram <- function(x,
                                         y,
                                         training_frame,
                                         gam_columns,
                                         validation_frame = NULL,
                                         seed = -1,
                                         keep_cross_validation_models = TRUE,
                                         keep_cross_validation_predictions = FALSE,
                                         keep_cross_validation_fold_assignment = FALSE,
                                         fold_assignment = c("AUTO", "Random", "Modulo", "Stratified"),
                                         fold_column = NULL,
                                         ignore_const_cols = TRUE,
                                         score_each_iteration = FALSE,
                                         offset_column = NULL,
                                         weights_column = NULL,
                                         standardize = FALSE,
                                         plug_values = NULL,
                                         max_iterations = 0,
                                         stopping_rounds = 0,
                                         stopping_metric = c("AUTO", "deviance", "logloss", "MSE", "RMSE", "MAE", "RMSLE", "AUC", "AUCPR", "lift_top_group", "misclassification", "mean_per_class_error", "custom", "custom_increasing"),
                                         stopping_tolerance = 0.001,
                                         balance_classes = FALSE,
                                         class_sampling_factors = NULL,
                                         max_after_balance_size = 5.0,
                                         max_runtime_secs = 0,
                                         custom_metric_func = NULL,
                                         auc_type = c("AUTO", "NONE", "MACRO_OVR", "WEIGHTED_OVR", "MACRO_OVO", "WEIGHTED_OVO"),
                                         infogram_algorithm = c("AUTO", "deeplearning", "drf", "gbm", "glm"),
                                         infogram_algorithm_params = NULL,
                                         model_algorithm = c("AUTO", "deeplearning", "drf", "gbm", "glm"),
                                         model_algorithm_params = NULL,
                                         sensitive_attributes = NULL,
                                         conditional_info_threshold = 0.1,
                                         varimp_threshold = 0.1,
                                         data_fraction = 1,
                                         parallelism = 0,
                                         ntop = 50,
                                         compute_p_values = FALSE,
                                         segment_columns = NULL,
                                         segment_models_id = NULL,
                                         parallelism = 1)
{
  # formally define variables that were excluded from function parameters
  model_id <- NULL
  verbose <- NULL
  destination_key <- NULL
  # Validate required training_frame first and other frame args: should be a valid key or an H2OFrame object
  training_frame <- .validate.H2OFrame(training_frame, required=TRUE)
  validation_frame <- .validate.H2OFrame(validation_frame, required=FALSE)

  # Validate other required args
  # If x is missing, no predictors will be used.  Only the gam columns are present as predictors
  if (missing(x) && infogram_algorithm_params=='GAM') {
      x = NULL
  } else {
      stop("predictor columns x must be specified except for GAM.")
  }

  # Validate other args
  # if (!is.null(beta_constraints)) {
  #     if (!inherits(beta_constraints, 'data.frame') && !is.H2OFrame(beta_constraints))
  #       stop(paste('`beta_constraints` must be an H2OH2OFrame or R data.frame. Got: ', class(beta_constraints)))
  #     if (inherits(beta_constraints, 'data.frame')) {
  #       beta_constraints <- as.h2o(beta_constraints)
  #     }
  # }
  if (inherits(beta_constraints, 'data.frame')) {
    beta_constraints <- as.h2o(beta_constraints)
  }

  # Build parameter list to send to model builder
  parms <- list()
  parms$training_frame <- training_frame
  args <- .verify_dataxy(training_frame, x, y)
  if( !missing(offset_column) && !is.null(offset_column))  args$x_ignore <- args$x_ignore[!( offset_column == args$x_ignore )]
  if( !missing(weights_column) && !is.null(weights_column)) args$x_ignore <- args$x_ignore[!( weights_column == args$x_ignore )]
  if( !missing(fold_column) && !is.null(fold_column)) args$x_ignore <- args$x_ignore[!( fold_column == args$x_ignore )]
  parms$ignored_columns <- args$x_ignore
  parms$response_column <- args$y
  parms$gam_columns <- gam_columns

  if (!missing(validation_frame))
    parms$validation_frame <- validation_frame
  if (!missing(seed))
    parms$seed <- seed
  if (!missing(keep_cross_validation_models))
    parms$keep_cross_validation_models <- keep_cross_validation_models
  if (!missing(keep_cross_validation_predictions))
    parms$keep_cross_validation_predictions <- keep_cross_validation_predictions
  if (!missing(keep_cross_validation_fold_assignment))
    parms$keep_cross_validation_fold_assignment <- keep_cross_validation_fold_assignment
  if (!missing(fold_assignment))
    parms$fold_assignment <- fold_assignment
  if (!missing(fold_column))
    parms$fold_column <- fold_column
  if (!missing(ignore_const_cols))
    parms$ignore_const_cols <- ignore_const_cols
  if (!missing(score_each_iteration))
    parms$score_each_iteration <- score_each_iteration
  if (!missing(offset_column))
    parms$offset_column <- offset_column
  if (!missing(weights_column))
    parms$weights_column <- weights_column
  if (!missing(standardize))
    parms$standardize <- standardize
  if (!missing(plug_values))
    parms$plug_values <- plug_values
  if (!missing(max_iterations))
    parms$max_iterations <- max_iterations
  if (!missing(stopping_rounds))
    parms$stopping_rounds <- stopping_rounds
  if (!missing(stopping_metric))
    parms$stopping_metric <- stopping_metric
  if (!missing(stopping_tolerance))
    parms$stopping_tolerance <- stopping_tolerance
  if (!missing(balance_classes))
    parms$balance_classes <- balance_classes
  if (!missing(class_sampling_factors))
    parms$class_sampling_factors <- class_sampling_factors
  if (!missing(max_after_balance_size))
    parms$max_after_balance_size <- max_after_balance_size
  if (!missing(max_runtime_secs))
    parms$max_runtime_secs <- max_runtime_secs
  if (!missing(custom_metric_func))
    parms$custom_metric_func <- custom_metric_func
  if (!missing(auc_type))
    parms$auc_type <- auc_type
  if (!missing(infogram_algorithm))
    parms$infogram_algorithm <- infogram_algorithm
  if (!missing(model_algorithm))
    parms$model_algorithm <- model_algorithm
  if (!missing(sensitive_attributes))
    parms$sensitive_attributes <- sensitive_attributes
  if (!missing(conditional_info_threshold))
    parms$conditional_info_threshold <- conditional_info_threshold
  if (!missing(varimp_threshold))
    parms$varimp_threshold <- varimp_threshold
  if (!missing(data_fraction))
    parms$data_fraction <- data_fraction
  if (!missing(parallelism))
    parms$parallelism <- parallelism
  if (!missing(ntop))
    parms$ntop <- ntop
  if (!missing(compute_p_values))
    parms$compute_p_values <- compute_p_values

  if (!missing(infogram_algorithm_params))
      parms$infogram_algorithm_params <- as.character(toJSON(infogram_algorithm_params, pretty = TRUE))
  if (!missing(model_algorithm_params))
      parms$model_algorithm_params <- as.character(toJSON(model_algorithm_params, pretty = TRUE))
  if( !missing(interactions) ) {
      # interactions are column names => as-is
      if( is.character(interactions) )       parms$interactions <- interactions
        else if( is.numeric(interactions) )    parms$interactions <- names(training_frame)[interactions]
        else stop("Don't know what to do with interactions. Supply vector of indices or names")
  }
      # For now, accept nfolds in the R interface if it is 0 or 1, since those values really mean do nothing.
      # For any other value, error out.
      # Expunge nfolds from the message sent to H2O, since H2O doesn't understand it.
  if (!missing(nfolds) && nfolds > 1)
      parms$nfolds <- nfolds
  if(!missing(beta_constraints))
      parms$beta_constraints <- beta_constraints
      if(!missing(missing_values_handling))
          parms$missing_values_handling <- missing_values_handling

  # Build segment-models specific parameters
  segment_parms <- list()
  if (!missing(segment_columns))
    segment_parms$segment_columns <- segment_columns
  if (!missing(segment_models_id))
    segment_parms$segment_models_id <- segment_models_id
  segment_parms$parallelism <- parallelism

  # Error check and build segment models
  segment_models <- .h2o.segmentModelsJob('infogram', segment_parms, parms, h2oRestApiVersion=99)
  return(segment_models)
}
